development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:c716280aabfe3af2c9ce9eceeb86444a@soapfish.redistogo.com:10633/
  channel_prefix: makan_production
