export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const OPEN_ERROR_SNACKBAR = "OPEN_ERROR_SNACKBAR";
export const CLOSE_ERROR_SNACKBAR = "CLOSE_ERROR_SNACKBAR";
