export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const OPEN_ERROR_SNACKBAR = "OPEN_ERROR_SNACKBAR";
export const CLOSE_ERROR_SNACKBAR = "CLOSE_ERROR_SNACKBAR";
export const OPEN_SUCCESS_SNACKBAR = "OPEN_SUCCESS_SNACKBAR";
export const CLOSE_SUCCESS_SNACKBAR = "CLOSE_SUCCESS_SNACKBAR";
export const CLOSE_ALL_SNACKBARS = "CLOSE_ALL_SNACKBARS";

export const SET_TAB_INDEX = "SET_TAB_INDEX";

export const SET_RESTAURANT_TAB_INDEX = "SET_RESTAURANT_TAB_INDEX";
export const SET_RESTAURANT_TAB_STATE = "SET_RESTAURANT_TAB_STATE";

export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_STATE = "SET_SEARCH_STATE";
export const SET_SEARCH_PATH = "SET_SEARCH_PATH";
export const SET_IS_SEARCHING = "SET_IS_SEARCHING";
export const SET_SEARCH_SECTION = "SET_SEARCH_SECTION";
